import {
  Column,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Lead } from '../leads/lead.entity';
import { User } from '../users/user.entity';

/** 1=>EasyPay, 2=>RazorPay, 3=>ccAvenue, 4=>PayU, 5=>ICICI UPI — legacy `repayment_provider_id` comment. */
export enum RepaymentProvider {
  EASYPAY = 1,
  RAZORPAY = 2,
  CCAVENUE = 3,
  PAYU = 4,
  ICICI_UPI = 5,
}

/** 1=>Website, 2=>LINK — legacy `repayment_method_id` comment. */
export enum RepaymentMethod {
  WEBSITE = 1,
  LINK = 2,
}

/** 1=>Success, 2=>Api Error, 3=>Conn Error, 4=>Code Error, 5=>Pending — legacy `repayment_api_status_id` comment (own numbering, not the shared ApiCallStatus). */
export enum RepaymentApiStatus {
  SUCCESS = 1,
  API_ERROR = 2,
  CONN_ERROR = 3,
  CODE_ERROR = 4,
  PENDING = 5,
}

/** 1=>Website, 2=>Link generated by Executive — legacy `repayment_source_id` comment. */
export enum RepaymentSource {
  WEBSITE = 1,
  EXECUTIVE_LINK = 2,
}

/**
 * Legacy `api_repayment_logs` — confirmed against
 * `old-php-files/components/includes/integration/payday_razorpay_api.php`,
 * which generates a Razorpay Payment Link for loan repayment collection.
 * Table name generalizes to "repayment" (not "razorpay") because the legacy
 * column implies more than one provider logs here, matching legacy's own
 * naming.
 */
@Entity('api_repayment_logs')
export class RepaymentLog {
  @PrimaryGeneratedColumn({
    name: 'repayment_log_id',
    type: 'bigint',
    unsigned: true,
  })
  id: number;

  @Column({
    name: 'repayment_lead_id',
    type: 'bigint',
    unsigned: true,
    nullable: true,
  })
  leadId: number | null;

  @ManyToOne(() => Lead, { nullable: true })
  @JoinColumn({ name: 'repayment_lead_id' })
  lead: Lead | null;

  @Column({
    name: 'repayment_user_id',
    type: 'int',
    unsigned: true,
    nullable: true,
  })
  userId: number | null;

  @ManyToOne(() => User, { nullable: true })
  @JoinColumn({ name: 'repayment_user_id' })
  user: User | null;

  @Column({ name: 'repayment_provider_id', type: 'mediumint' })
  provider: RepaymentProvider;

  @Column({ name: 'repayment_method_id', type: 'smallint', unsigned: true })
  method: RepaymentMethod;

  @Column({
    name: 'repayment_loan_id',
    type: 'varchar',
    length: 255,
    nullable: true,
  })
  loanNumber: string | null;

  @Column({
    name: 'repayment_trans_no',
    type: 'varchar',
    length: 255,
    nullable: true,
  })
  transactionNo: string | null;

  @Column({
    name: 'repayment_tid',
    type: 'varchar',
    length: 500,
    nullable: true,
  })
  tid: string | null;

  @Column({
    name: 'repayment_order_id',
    type: 'varchar',
    length: 500,
    nullable: true,
  })
  orderId: string | null;

  @Column({ name: 'repayment_request', type: 'text', nullable: true })
  request: string | null;

  @Column({ name: 'repayment_response', type: 'text', nullable: true })
  response: string | null;

  @Column({
    name: 'repayment_api_status_id',
    type: 'mediumint',
    unsigned: true,
    nullable: true,
  })
  status: RepaymentApiStatus | null;

  @Column({
    name: 'repayment_errors',
    type: 'varchar',
    length: 500,
    nullable: true,
  })
  errors: string | null;

  @Column({
    name: 'repayment_amount',
    type: 'int',
    unsigned: true,
    nullable: true,
  })
  amount: number | null;

  @Column({
    name: 'repayment_transaction_date',
    type: 'datetime',
    nullable: true,
  })
  transactionDate: Date | null;

  @Column({
    name: 'repayment_source_id',
    type: 'smallint',
    unsigned: true,
    default: RepaymentSource.WEBSITE,
  })
  source: RepaymentSource;

  @Column({
    name: 'repayment_request_datetime',
    type: 'datetime',
    nullable: true,
  })
  requestedAt: Date | null;

  @Column({
    name: 'repayment_response_datetime',
    type: 'datetime',
    nullable: true,
  })
  respondedAt: Date | null;

  @Column({
    name: 'repayment_active',
    type: 'tinyint',
    unsigned: true,
    default: 1,
  })
  isActive: boolean;

  @Column({
    name: 'repayment_deleted',
    type: 'tinyint',
    unsigned: true,
    default: 0,
  })
  isDeleted: boolean;
}
