import { timingSafeEqual } from 'node:crypto';
import {
  type CanActivate,
  type ExecutionContext,
  Injectable,
  UnauthorizedException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { Request } from 'express';

export const VENDOR_CALLBACK_TOKEN_HEADER = 'x-callback-token';

/**
 * Shared-secret authentication for the inbound vendor webhooks that carry no
 * signature of their own.
 *
 * Two of this repo's `@Public()` callbacks already authenticate themselves:
 * Razorpay via `x-razorpay-signature` HMAC, ICICI UPI via RSA decryption of
 * the body. The rest (Signzy video-KYC, Signzy eSign, CartBI bank analysis,
 * CartBI account aggregator) had nothing at all — legacy had nothing either,
 * which is why they were ported that way, but "legacy didn't check" is not a
 * reason to leave an unauthenticated endpoint that flips KYC and eSign
 * completion flags on a loan file. `@Roles`/`JwtAuthGuard` can't apply: a
 * vendor's server has no staff session cookie.
 *
 * So: a long random token, generated by us and configured on the vendor's
 * side, sent back on every callback. Accepted either as the
 * `x-callback-token` header or a `?token=` query parameter, because vendor
 * consoles differ in whether they let you set custom headers on a webhook —
 * a query parameter is weaker (it lands in access logs) but it is the only
 * option some of them offer, and it is still vastly better than nothing.
 *
 * **Fails closed when `VENDOR_CALLBACK_TOKEN` is unset.** That is
 * deliberate: a guard that waves requests through when its secret is
 * missing is exactly the bypass this exists to remove, and this repo's
 * convention for integrations is already "won't function until real
 * credentials are supplied". Set it before these callbacks will work.
 */
@Injectable()
export class VendorCallbackTokenGuard implements CanActivate {
  constructor(private readonly configService: ConfigService) {}

  canActivate(context: ExecutionContext): boolean {
    const expected = this.configService.get<string>('VENDOR_CALLBACK_TOKEN');
    if (!expected) {
      throw new UnauthorizedException(
        'Vendor callback authentication is not configured',
      );
    }

    const request = context.switchToHttp().getRequest<Request>();
    const headerValue = request.headers[VENDOR_CALLBACK_TOKEN_HEADER];
    const queryValue = request.query?.token;
    const presented =
      (typeof headerValue === 'string' ? headerValue : undefined) ??
      (typeof queryValue === 'string' ? queryValue : undefined);

    if (!presented || !constantTimeEquals(presented, expected)) {
      throw new UnauthorizedException('Invalid vendor callback token');
    }
    return true;
  }
}

/** Length is compared first because `timingSafeEqual` throws on a mismatch
 * rather than returning false. Length is not secret. */
function constantTimeEquals(a: string, b: string): boolean {
  const left = Buffer.from(a, 'utf-8');
  const right = Buffer.from(b, 'utf-8');
  if (left.length !== right.length) {
    return false;
  }
  return timingSafeEqual(left, right);
}
